# Generated by Django 5.1.4 on 2025-03-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='comm',
            field=models.FloatField(default=None, max_length=100),
        ),
    ]
