# Generated by Django 5.1.4 on 2025-03-23 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_emp_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='deptno',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emp',
            name='deptno',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.dept'),
        ),
    ]
